apiVersion: v1
kind: Secret
metadata:
  name: db-password
type: Opaque
stringData:
  password: "secretpassword123"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-password
type: Opaque
stringData:
  password: "redispassword123"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "guestbook"
  DB_USER: "guestbook"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
